### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by ibenrodriguez** [sigwo/ip-subnet-calc#1]
I'm not sure if I'm running the program wrong or if there's another issue.  Can you offer any advise?

$ python ip-subnet-calc.py
IP address: 100.100.100.100
CIDR notation, NO / mark!: 24
Traceback (most recent call last):
  File "ip-subnet-calc.py", line 49, in <module>
    host = "{:,}".format(xhost)
ValueError: zero length field name in format

$ python -V
Python 2.6.6

**Comment by sigwo** [comment]
How to use:
You will need Python 2.7 (from the README. md)
